// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	model "test-backend/internal/model"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CancelBooking mocks base method.
func (m *MockRepository) CancelBooking(ctx context.Context, bookingID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, bookingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockRepositoryMockRecorder) CancelBooking(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockRepository)(nil).CancelBooking), ctx, bookingID)
}

// CreateBooking mocks base method.
func (m *MockRepository) CreateBooking(ctx context.Context, b model.Booking) (model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, b)
	ret0, _ := ret[0].(model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockRepositoryMockRecorder) CreateBooking(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockRepository)(nil).CreateBooking), ctx, b)
}

// CreateRoom mocks base method.
func (m *MockRepository) CreateRoom(ctx context.Context, room model.Room) (model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room)
	ret0, _ := ret[0].(model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRepositoryMockRecorder) CreateRoom(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRepository)(nil).CreateRoom), ctx, room)
}

// CreateSchedule mocks base method.
func (m *MockRepository) CreateSchedule(ctx context.Context, schedule model.Schedule) (model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, schedule)
	ret0, _ := ret[0].(model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockRepositoryMockRecorder) CreateSchedule(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockRepository)(nil).CreateSchedule), ctx, schedule)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, user model.User) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, user)
}

// EnsureUser mocks base method.
func (m *MockRepository) EnsureUser(ctx context.Context, user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureUser indicates an expected call of EnsureUser.
func (mr *MockRepositoryMockRecorder) EnsureUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureUser", reflect.TypeOf((*MockRepository)(nil).EnsureUser), ctx, user)
}

// GetBooking mocks base method.
func (m *MockRepository) GetBooking(ctx context.Context, bookingID uuid.UUID) (model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooking", ctx, bookingID)
	ret0, _ := ret[0].(model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooking indicates an expected call of GetBooking.
func (mr *MockRepositoryMockRecorder) GetBooking(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooking", reflect.TypeOf((*MockRepository)(nil).GetBooking), ctx, bookingID)
}

// GetSlotByID mocks base method.
func (m *MockRepository) GetSlotByID(ctx context.Context, slotID uuid.UUID) (model.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlotByID", ctx, slotID)
	ret0, _ := ret[0].(model.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlotByID indicates an expected call of GetSlotByID.
func (mr *MockRepositoryMockRecorder) GetSlotByID(ctx, slotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlotByID", reflect.TypeOf((*MockRepository)(nil).GetSlotByID), ctx, slotID)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
}

// ListAvailableSlotsByRoomAndDate mocks base method.
func (m *MockRepository) ListAvailableSlotsByRoomAndDate(ctx context.Context, roomID uuid.UUID, date time.Time) ([]model.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableSlotsByRoomAndDate", ctx, roomID, date)
	ret0, _ := ret[0].([]model.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailableSlotsByRoomAndDate indicates an expected call of ListAvailableSlotsByRoomAndDate.
func (mr *MockRepositoryMockRecorder) ListAvailableSlotsByRoomAndDate(ctx, roomID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableSlotsByRoomAndDate", reflect.TypeOf((*MockRepository)(nil).ListAvailableSlotsByRoomAndDate), ctx, roomID, date)
}

// ListBookings mocks base method.
func (m *MockRepository) ListBookings(ctx context.Context, page, pageSize int) ([]model.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookings", ctx, page, pageSize)
	ret0, _ := ret[0].([]model.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookings indicates an expected call of ListBookings.
func (mr *MockRepositoryMockRecorder) ListBookings(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookings", reflect.TypeOf((*MockRepository)(nil).ListBookings), ctx, page, pageSize)
}

// ListMyFutureBookings mocks base method.
func (m *MockRepository) ListMyFutureBookings(ctx context.Context, userID uuid.UUID, now time.Time) ([]model.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyFutureBookings", ctx, userID, now)
	ret0, _ := ret[0].([]model.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyFutureBookings indicates an expected call of ListMyFutureBookings.
func (mr *MockRepositoryMockRecorder) ListMyFutureBookings(ctx, userID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyFutureBookings", reflect.TypeOf((*MockRepository)(nil).ListMyFutureBookings), ctx, userID, now)
}

// ListRooms mocks base method.
func (m *MockRepository) ListRooms(ctx context.Context) ([]model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx)
	ret0, _ := ret[0].([]model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockRepositoryMockRecorder) ListRooms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockRepository)(nil).ListRooms), ctx)
}

// RoomExists mocks base method.
func (m *MockRepository) RoomExists(ctx context.Context, roomID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomExists", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoomExists indicates an expected call of RoomExists.
func (mr *MockRepositoryMockRecorder) RoomExists(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomExists", reflect.TypeOf((*MockRepository)(nil).RoomExists), ctx, roomID)
}

// SaveSlots mocks base method.
func (m *MockRepository) SaveSlots(ctx context.Context, slots []model.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSlots", ctx, slots)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSlots indicates an expected call of SaveSlots.
func (mr *MockRepositoryMockRecorder) SaveSlots(ctx, slots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSlots", reflect.TypeOf((*MockRepository)(nil).SaveSlots), ctx, slots)
}
